version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - app-network
    depends_on:
      - nginx

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
